sudo: required
dist: trusty

services:
  - docker

env:
  global:
    - secure: "TnsH4ERdppZwQnBoyAzFiMDHdc3uJweZu/ppI13VW6M3hMwIH5H9PxDvak3lDuc37kw0O9YBTV6I9T5R4UYY223zAmFAqDAnZx5HrHJRJIZJ6GVnxCxNgsSOvR6ERtIXOY0vpfz9VwvNUYahSdr/1nq9YRQuf8GYIVFcTXLpKz604SqbkuimC0B7V9Iea2CRHUPyqDbLTwA0OiCikJAMaVEchWH2sn3tYqyEn57e4VkStZ+LqTJK23JKES6Qk4xbreBaWurmacJo7t0qRvAKHTw2HyG8uPj1pfv6WnnD60yL3DFTMuE3Oc2sjFTX1GXbi3xwQnqHOjrVmpF3sbMqZZ+fSEyfXSIuDZ11xAZu5r2PWNpDG4ylR+GuPcFvU8nVgsYn+Eat5NJ/tK0Te3W3zNXBoR6yfln9bke6AGGYpMO06gjF34CPSXmRZZgP3AJjw48+9rvqAmF9RSu9/111yNKdXcTspIaN/B3NMigfMz4AXj6Dfcs38cNS9ztwk+T2Z02RJU9av74k1JzymHi9u6lVfQ9nUgCxBUrbaL3jdTEcKsxFdcR1aFPqfS3igq77iMQIZCb5+5wWidjHIZ0vTpjxLla21HsKbAArbRHI/6xh0Ym8mO+T174at1KkwDuz4p8G2WcEOtbVqtLkHDm57yL0Y32rToZQT9MM2wbCLq0="
    - secure: "pSjdbmkrSYVZ6wKM3Ts8KhyRhstgcelKN2Y6UOvyJHKz8ww8ym0OfM1jiC3yK5/mhxQ7H7HYyCsWiPrc496PMjJEOdm21UVdKtF2dCUmwUNvm9FdbhDVzVV4449xIppjA1U9tVOITAKT0jQpfQ92lltrfKo2xmOHrwhz0xElhlG7vXWaGjgwavXmldGBcONFOiWF0SebLmOtfYy+hKnnGGIdvibccjkwN4wxhTHi7JBi3X7L0ONE1k/BT17qb2VR9RBwRFCqYuqxwwx5YoHBx8X46VF0NK98H6IL6b2L/tHQ0F3X6CisLNmBBWXWd0tLL7MJ/sBGY1iK6Z3QBxf/p+mLhAbVRc+kRxGb2ZPt+1iB+FQFxMOWtvXDN0J0IcMnk3t+4u8b1VSF2xyLSpFvpzqrIEjWfNJrsoxc5oQwZSmK+1OfKDRs03GYfUU1qkD6jxKGefweCL96xPyjfVygAuU+yAhhvjwvXZCy7Szs/bGhk+CZwADBjP4TkuP/yN6e/wVSnYiQV9mzJthwYFUkngDIK7zsumVGuQyCfTjmY9Q2b0QSrVhO1E1aRwtrt5kp5bqSKqnEargGRrgaZ2OYmeqwRE41uO5kdFJeGztJCAkMbkBHLouBKu2PDIJe2amYf8mH/18+EtsC5BOZ4imLgStHU+pucxqrXOBTib7BzDY="
    - secure: "T1eJT4uvqOjZ3EZWMav1Vt8pj1vOTUP0RZASHYwUUJYTaBjqKJ762WMrvK0gVXoje49pXtma1PSMjlBmDkPRBD5OCrI20wMJOv4V/WcPNp02/E+62BvBzXTLNxW1a249L6rZ8ykPLXVQxMOhjYq15rNlAEyU0w0ZQPBHpGUDF6xDVukDhuIsePBdjx+c+db5VlW+fX0kVE4Jakbr9M0OlATlltogtRowi088PboQcGJeCj/pgTcQa8fTXSIrCfjdnelSEX9Z/NYyzSE+0yiQfKvuDr+NpG0klSB0DZqJygLnrXB3BuehLQJE6jvxBUg+lggjnOhV+kyxQpY4wZWOI217zz5aF9AgzYT0YjgjVk/ZYl+txR6r6t606B7uHVdzRmf+C27m2j4yHdELKm9kHhvHejiNleJSZ2P9KiN+gHtmwy2mFCkzESOVzCzu7R1TdaxIr9oroapDSSIxgrAeplCKwOC17aslvOCmLuxZ0llMmWpcbbHzDusVvM2Kjost8roa4sSOeb2CnIw89YRjS6FSXMCND1VHkJ/5fKzZNQj+shPrx2Xjo1SDFSphggdGAV7RsmgWnBCBsqfFxeoqOGAVW5/DqqOkEtJ1L5410wKIGzFVswU2Jiz0bsbj9ZaOemTQxLwfNm67PBJw9N/HHhAUspSeRqXA4yaqlu7GkLg="


before_install:
  - docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - docker pull rainbeam/eth-static || echo "ok"

install:
  - docker build --rm --file=Dockerfile --tag=rainbeam/eth-static .
  # create a container to copy files from (can't copy from an image)
  - tmp_container=$(docker create rainbeam/eth-static sh)
  - docker cp ${tmp_container}:/usr/local/bin/eth .

script:
  - test true

after_success:
  # trying to speed up build by caching the successful docker images
  - docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - export REPO=rainbeam/eth-static
  - export COMMIT=${TRAVIS_COMMIT::8}
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      export TAG="latest"
      else export TAG=$TRAVIS_BRANCH
    fi
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
